var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="",ea,fa;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
fa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ha=g.print||console.log.bind(console),l=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var ia;g.wasmBinary&&(ia=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ka("no native wasm support detected");
var la,r,ma=!1,v,y,na,z,B,oa,D;function pa(){var a=la.buffer;g.HEAP8=v=new Int8Array(a);g.HEAP16=na=new Int16Array(a);g.HEAP32=z=new Int32Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAPU32=B=new Uint32Array(a);g.HEAPF32=oa=new Float32Array(a);g.HEAPF64=D=new Float64Array(a)}var qa,ra=[],sa=[],ta=[],ua=[],va=[];function wa(){var a=g.preRun.shift();ra.unshift(a)}var E=0,xa=null,ya=null;function za(){E++;g.monitorRunDependencies&&g.monitorRunDependencies(E)}
function Aa(){E--;g.monitorRunDependencies&&g.monitorRunDependencies(E);if(0==E&&(null!==xa&&(clearInterval(xa),xa=null),ya)){var a=ya;ya=null;a()}}function ka(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";l(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ba(a){return a.startsWith("data:application/octet-stream;base64,")}var Ca;Ca="index.wasm";if(!Ba(Ca)){var Da=Ca;Ca=g.locateFile?g.locateFile(Da,k):k+Da}
function Ea(a){if(a==Ca&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}function Fa(a){return ia||"function"!=typeof fetch?Promise.resolve().then(()=>Ea(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a))}function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l("failed to asynchronously prepare wasm: "+d);ka(d)})}
function Ha(a,b){var c=Ca;ia||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l("wasm streaming compile failed: "+e);l("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}var F,Ia;function Ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ka=a=>{for(;0<a.length;)a.shift()(g)},La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Oa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,
b.length-1));return a+b},Pa=a=>{if("/"===a)return"/";a=G(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Qa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);ka("initRandomDevice")},Ra=a=>(Ra=Qa())(a);
function Sa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=La(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Ta=new TextDecoder("utf8"),Ua=a=>{for(var b=0;a[b]&&!(NaN<=b);)++b;return Ta.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Va=[],Wa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Xa=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=
h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function Ya(a){var b=Array(Wa(a)+1);a=Xa(a,b,0,b.length);b.length=a;return b}var Za=[];function $a(a,b){Za[a]={input:[],xa:[],Ba:b};ab(a,bb)}
var bb={open:function(a){var b=Za[a.node.Pa];if(!b)throw new H(43);a.va=b;a.seekable=!1},close:function(a){a.va.Ba.Na(a.va)},Na:function(a){a.va.Ba.Na(a.va)},read:function(a,b,c,d){if(!a.va||!a.va.Ba.ab)throw new H(60);for(var e=0,f=0;f<d;f++){try{var h=a.va.Ba.ab(a.va)}catch(n){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.va||!a.va.Ba.Va)throw new H(60);try{for(var e=0;e<d;e++)a.va.Ba.Va(a.va,
b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},cb={ab:function(){a:{if(!Va.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Va=Ya(a)}a=Va.shift()}return a},Va:function(a,b){null===b||10===b?(ha(Ua(a.xa)),a.xa=[]):0!=b&&a.xa.push(b)},Na:function(a){a.xa&&0<a.xa.length&&(ha(Ua(a.xa)),a.xa=[])},qb:function(){return{Fb:25856,
Hb:5,Eb:191,Gb:35387,Db:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},rb:function(){return 0},sb:function(){return[24,80]}},db={Va:function(a,b){null===b||10===b?(l(Ua(a.xa)),a.xa=[]):0!=b&&a.xa.push(b)},Na:function(a){a.xa&&0<a.xa.length&&(l(Ua(a.xa)),a.xa=[])}};function eb(a,b){var c=a.ra?a.ra.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ra,a.ra=new Uint8Array(b),0<a.wa&&a.ra.set(c.subarray(0,a.wa),0))}
var I={za:null,Aa(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.za||(I.za={dir:{node:{Ca:I.sa.Ca,ya:I.sa.ya,Ja:I.sa.Ja,Oa:I.sa.Oa,ib:I.sa.ib,Ra:I.sa.Ra,jb:I.sa.jb,gb:I.sa.gb,Qa:I.sa.Qa},stream:{Fa:I.ua.Fa}},file:{node:{Ca:I.sa.Ca,ya:I.sa.ya},stream:{Fa:I.ua.Fa,read:I.ua.read,write:I.ua.write,Ya:I.ua.Ya,Ua:I.ua.Ua,fb:I.ua.fb}},link:{node:{Ca:I.sa.Ca,ya:I.sa.ya,La:I.sa.La},stream:{}},Za:{node:{Ca:I.sa.Ca,ya:I.sa.ya},stream:fb}});
c=gb(a,b,c,d);16384===(c.mode&61440)?(c.sa=I.za.dir.node,c.ua=I.za.dir.stream,c.ra={}):32768===(c.mode&61440)?(c.sa=I.za.file.node,c.ua=I.za.file.stream,c.wa=0,c.ra=null):40960===(c.mode&61440)?(c.sa=I.za.link.node,c.ua=I.za.link.stream):8192===(c.mode&61440)&&(c.sa=I.za.Za.node,c.ua=I.za.Za.stream);c.timestamp=Date.now();a&&(a.ra[b]=c,a.timestamp=c.timestamp);return c},Kb(a){return a.ra?a.ra.subarray?a.ra.subarray(0,a.wa):new Uint8Array(a.ra):new Uint8Array(0)},sa:{Ca(a){var b={};b.Jb=8192===(a.mode&
61440)?a.id:1;b.Nb=a.id;b.mode=a.mode;b.Qb=1;b.uid=0;b.Lb=0;b.Pa=a.Pa;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.wa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Bb=new Date(a.timestamp);b.Pb=new Date(a.timestamp);b.Ib=new Date(a.timestamp);b.lb=4096;b.Cb=Math.ceil(b.size/b.lb);return b},ya(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.wa!=b))if(0==b)a.ra=null,a.wa=0;else{var c=a.ra;a.ra=new Uint8Array(b);
c&&a.ra.set(c.subarray(0,Math.min(b,a.wa)));a.wa=b}},Ja(){throw hb[44];},Oa(a,b,c,d){return I.createNode(a,b,c,d)},ib(a,b,c){if(16384===(a.mode&61440)){try{var d=ib(b,c)}catch(f){}if(d)for(var e in d.ra)throw new H(55);}delete a.parent.ra[a.name];a.parent.timestamp=Date.now();a.name=c;b.ra[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Ra(a,b){delete a.ra[b];a.timestamp=Date.now()},jb(a,b){var c=ib(a,b),d;for(d in c.ra)throw new H(55);delete a.ra[b];a.timestamp=Date.now()},gb(a){var b=[".",".."],
c;for(c in a.ra)a.ra.hasOwnProperty(c)&&b.push(c);return b},Qa(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},La(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},ua:{read(a,b,c,d,e){var f=a.node.ra;if(e>=a.node.wa)return 0;a=Math.min(a.node.wa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===v.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ra||a.ra.subarray)){if(f)return a.ra=
b.subarray(c,c+d),a.wa=d;if(0===a.wa&&0===e)return a.ra=b.slice(c,c+d),a.wa=d;if(e+d<=a.wa)return a.ra.set(b.subarray(c,c+d),e),d}eb(a,e+d);if(a.ra.subarray&&b.subarray)a.ra.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ra[e+f]=b[c+f];a.wa=Math.max(a.wa,e+d);return d},Fa(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.wa);if(0>b)throw new H(28);return b},Ya(a,b,c){eb(a.node,b+c);a.node.wa=Math.max(a.node.wa,b+c)},Ua(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);
a=a.node.ra;if(e&2||a.buffer!==v.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;ka();b=void 0;if(!b)throw new H(48);v.set(a,b)}else c=!1,b=a.byteOffset;return{Tb:b,yb:c}},fb(a,b,c,d){I.ua.write(a,b,0,d,c,!1);return 0}}},jb=(a,b,c)=>{var d=`al ${a}`;fa(a,e=>{e||ka(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Aa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&za(d)},kb=g.preloadPlugins||[];
function lb(a,b,c,d){"undefined"!=typeof Browser&&Browser.Mb();var e=!1;kb.forEach(function(f){!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e}function mb(a,b,c,d,e,f,h,n,p,m){function t(w){function x(C){m&&m();n||nb(a,b,C,d,e,p);f&&f();Aa(u)}lb(w,q,x,()=>{h&&h();Aa(u)})||x(w)}var q=b?Sa(G(a+"/"+b)):a,u=`cp ${q}`;za(u);"string"==typeof c?jb(c,w=>t(w),h):t(c)}function pb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var qb=null,rb={},sb=[],tb=1,J=null,ub=!0,H=null,hb={},K=(a,b={})=>{a=Sa(a);if(!a)return{path:"",node:null};b=Object.assign({$a:!0,Wa:0},b);if(8<b.Wa)throw new H(32);a=a.split("/").filter(h=>!!h);for(var c=qb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=ib(c,a[e]);d=G(d+"/"+a[e]);c.Ka&&(!f||f&&b.$a)&&(c=c.Ka.root);if(!f||b.Sa)for(f=0;40960===(c.mode&61440);)if(c=vb(d),d=Sa(Oa(d),c),c=K(d,{Wa:b.Wa+1}).node,40<f++)throw new H(32);}return{path:d,node:c}},wb=a=>{for(var b;;){if(a===
a.parent)return a=a.Aa.eb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},xb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%J.length},ib=(a,b)=>{var c;if(c=(c=yb(a,"x"))?c:a.sa.Ja?0:2)throw new H(c,a);for(c=J[xb(a.id,b)];c;c=c.Ga){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.sa.Ja(a,b)},gb=(a,b,c,d)=>{a=new zb(a,b,c,d);b=xb(a.parent.id,a.name);a.Ga=J[b];return J[b]=a},Ab=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");
return b},yb=(a,b)=>{if(ub)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Bb=(a,b)=>{try{return ib(a,b),20}catch(c){}return yb(a,"wx")},Cb=()=>{for(var a=0;4096>=a;a++)if(!sb[a])return a;throw new H(33);},L=a=>{a=sb[a];if(!a)throw new H(8);return a},Eb=a=>{var b=-1;Db||(Db=function(){this.Ia={}},Db.prototype={},Object.defineProperties(Db.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.Ia.flags},
set(c){this.Ia.flags=c}},position:{get(){return this.Ia.position},set(c){this.Ia.position=c}}}));a=Object.assign(new Db,a);-1==b&&(b=Cb());a.Ea=b;return sb[b]=a},fb={open:a=>{a.ua=rb[a.node.Pa].ua;a.ua.open&&a.ua.open(a)},Fa:()=>{throw new H(70);}},ab=(a,b)=>{rb[a]={ua:b}},Fb=(a,b)=>{var c="/"===b,d=!b;if(c&&qb)throw new H(10);if(!c&&!d){var e=K(b,{$a:!1});b=e.path;e=e.node;if(e.Ka)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,Sb:{},eb:b,ub:[]};a=a.Aa(b);a.Aa=b;b.root=a;c?qb=
a:e&&(e.Ka=b,e.Aa&&e.Aa.ub.push(b))},M=(a,b,c)=>{var d=K(a,{parent:!0}).node;a=Pa(a);if(!a||"."===a||".."===a)throw new H(28);var e=Bb(d,a);if(e)throw new H(e);if(!d.sa.Oa)throw new H(63);return d.sa.Oa(d,a,b,c)},Gb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return M(a,b|8192,c)},Hb=(a,b)=>{if(!Sa(a))throw new H(44);var c=K(b,{parent:!0}).node;if(!c)throw new H(44);b=Pa(b);var d=Bb(c,b);if(d)throw new H(d);if(!c.sa.Qa)throw new H(63);c.sa.Qa(c,b,a)},Ib=a=>{var b=K(a,{parent:!0}).node;if(!b)throw new H(44);
var c=Pa(a);a=ib(b,c);a:{try{var d=ib(b,c)}catch(f){d=f.Da;break a}var e=yb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new H(d);if(!b.sa.Ra)throw new H(63);if(a.Ka)throw new H(10);b.sa.Ra(b,c);b=xb(a.parent.id,a.name);if(J[b]===a)J[b]=a.Ga;else for(b=J[b];b;){if(b.Ga===a){b.Ga=a.Ga;break}b=b.Ga}},vb=a=>{a=K(a).node;if(!a)throw new H(44);if(!a.sa.La)throw new H(28);return Sa(wb(a.parent),a.sa.La(a))},Jb=(a,b)=>{a="string"==typeof a?K(a,{Sa:!0}).node:a;if(!a.sa.ya)throw new H(63);a.sa.ya(a,
{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Lb=(a,b,c)=>{if(""===a)throw new H(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=G(a);try{e=K(a,{Sa:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=M(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&
65536&&16384!==(e.mode&61440))throw new H(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ab(b)||b&512)?31:yb(e,Ab(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?K(c,{Sa:!0}).node:c;if(!c.sa.ya)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=yb(c,"w"))throw new H(d);c.sa.ya(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Eb({node:e,path:wb(e),flags:b,seekable:!0,position:0,ua:e.ua,xb:[],error:!1});e.ua.open&&
e.ua.open(e);!g.logReadFiles||b&1||(Kb||(Kb={}),a in Kb||(Kb[a]=1));return e},Mb=a=>{if(null===a.Ea)throw new H(8);a.Ta&&(a.Ta=null);try{a.ua.close&&a.ua.close(a)}catch(b){throw b;}finally{sb[a.Ea]=null}a.Ea=null},Nb=(a,b,c)=>{if(null===a.Ea)throw new H(8);if(!a.seekable||!a.ua.Fa)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.ua.Fa(a,b,c);a.xb=[]},Ob=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new H(28);if(null===a.Ea)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(16384===(a.node.mode&
61440))throw new H(31);if(!a.ua.write)throw new H(28);a.seekable&&a.flags&1024&&Nb(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H(70);b=a.ua.write(a,b,c,d,e,f);h||(a.position+=b);return b},Pb=()=>{H||(H=function(a,b){this.name="ErrnoError";this.node=b;this.wb=function(c){this.Da=c};this.wb(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(a=>{hb[a]=new H(a);hb[a].stack="<generic error, no stack>"}))},Qb,Rb=(a,b)=>{a="string"==
typeof a?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{M(d,16895,0)}catch(e){}a=d}}return d},Sb=(a,b,c,d)=>{a=G(("string"==typeof a?a:wb(a))+"/"+b);c=pb(c,d);return M(a,(void 0!==c?c:438)&4095|32768,0)},nb=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:wb(a),h=b?G(a+"/"+b):a);a=pb(d,e);h=M(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Jb(h,a|146);b=Lb(h,577);Ob(b,
c,0,c.length,0,f);Mb(b);Jb(h,a)}return h},N=(a,b,c,d)=>{a=G(("string"==typeof a?a:wb(a))+"/"+b);b=pb(!!c,!!d);N.cb||(N.cb=64);var e=N.cb++<<8|0;ab(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,n,p)=>{for(var m=0,t=0;t<p;t++){try{var q=c()}catch(u){throw new H(29);}if(void 0===q&&0===m)throw new H(6);if(null===q||void 0===q)break;m++;h[n+t]=q}m&&(f.node.timestamp=Date.now());return m},write:(f,h,n,p)=>{for(var m=0;m<p;m++)try{d(h[n+m])}catch(t){throw new H(29);
}p&&(f.node.timestamp=Date.now());return m}});return Gb(a,b,e)},Tb=a=>{if(!(a.bb||a.tb||a.link||a.ra)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ea)try{a.ra=Ya(ea(a.url)),a.wa=a.ra.length}catch(b){throw new H(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Ub=(a,b,c,d,
e)=>{if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={bb:!1,url:c};var f=Sb(a,b,d,e);c.ra?f.ra=c.ra:c.url&&(f.ra=null,f.url=c.url);Object.defineProperties(f,{wa:{get:function(){return this.ra.length}}});var h={};Object.keys(f.ua).forEach(n=>{var p=f.ua[n];h[n]=function(){Tb(f);return p.apply(null,arguments)}});h.read=(n,p,m,t,q)=>{Tb(f);n=n.node.ra;if(q>=n.length)p=0;else{t=Math.min(n.length-
q,t);if(n.slice)for(var u=0;u<t;u++)p[m+u]=n[q+u];else for(u=0;u<t;u++)p[m+u]=n.get(q+u);p=t}return p};h.Ua=()=>{Tb(f);ka();throw new H(48);};f.ua=h;return f},Vb={},Db,Kb,O=a=>{if(!a)return"";for(var b=a+NaN,c=a;!(c>=b)&&y[c];)++c;return Ta.decode(y.subarray(a,c))},Wb=void 0;function Xb(){Wb+=4;return z[Wb-4>>2]}var Yb=0;function Zb(){for(var a=P.length-1;0<=a;--a)$b(a);P=[];ac=[]}var ac=[];
function bc(){if(navigator.userActivation?navigator.userActivation.isActive:Yb&&cc.zb)for(var a=0;a<ac.length;++a){var b=ac[a];ac.splice(a,1);--a;b.Vb.apply(null,b.Ab)}}var P=[];function $b(a){var b=P[a];b.target.removeEventListener(b.Ma,b.nb,b.kb);P.splice(a,1)}
function dc(a){function b(d){++Yb;cc=a;bc();a.ob(d);bc();--Yb}if(!a.target)return-4;if(a.mb)a.nb=b,a.target.addEventListener(a.Ma,b,a.kb),P.push(a),ec||(ua.push(Zb),ec=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].Ma==a.Ma&&$b(c--);return 0}var ec,cc,fc,gc=[0,document,window];function hc(a){a=2<a?O(a):a;return gc[a]||document.querySelector(a)}var ic=[],jc=a=>{var b=ic[a];b||(a>=ic.length&&(ic.length=a+1),ic[a]=b=qa.get(a));return b};
function kc(a,b,c,d){fc||(fc=lc(36));a=hc(a);return dc({target:a,Ma:"resize",mb:d,ob:function(e=event){if(e.target==a){var f=document.body;if(f){var h=fc;z[h>>2]=e.detail;z[h+4>>2]=f.clientWidth;z[h+8>>2]=f.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset;z[h+32>>2]=pageYOffset;jc(d)(10,h,b)&&e.preventDefault()}}},kb:c})}function mc(a){return{width:B[a>>2],height:B[a+4>>2],depthOrArrayLayers:B[a+8>>2]}}
function nc(a,b){if(a){for(var c={},d=0;d<a;++d){var e=b+16*d,f=O(B[e+4>>2]);c[f]=D[e+8>>3]}return c}}function oc(a){return a?pc.get(a):"auto"}
var qc=["repeat","mirror-repeat","clamp-to-edge"],rc="zero one src one-minus-src src-alpha one-minus-src-alpha dst one-minus-dst dst-alpha one-minus-dst-alpha src-alpha-saturated constant one-minus-constant".split(" "),sc=["add","subtract","reverse-subtract","min","max"],tc=[,"never","less","less-equal","greater","greater-equal","equal","not-equal","always"],uc=["beginning","end"],wc=["none","front","back"],xc=["nearest","linear"],yc=["ccw","cw"],zc=[,"uint16","uint32"],Ac=[,"clear","load"],Bc=["nearest",
"linear"],Cc=["vertex-shader-invocations","clipper-invocations","clipper-primitives-out","fragment-shader-invocations","compute-shader-invocations"],Dc=["point-list","line-list","line-strip","triangle-list","triangle-strip"],Ec=["occlusion","pipeline-statistics","timestamp"],Fc=["beginning","end"],Gc="keep zero replace invert increment-clamp decrement-clamp increment-wrap decrement-wrap".split(" "),Hc=[,"store","discard"],Ic=["all","stencil-only","depth-only"],Jc=["1d","2d","3d"],Q=[,"r8unorm","r8snorm",
"r8uint","r8sint","r16uint","r16sint","r16float","rg8unorm","rg8snorm","rg8uint","rg8sint","r32float","r32uint","r32sint","rg16uint","rg16sint","rg16float","rgba8unorm","rgba8unorm-srgb","rgba8snorm","rgba8uint","rgba8sint","bgra8unorm","bgra8unorm-srgb","rgb10a2unorm","rg11b10ufloat","rgb9e5ufloat","rg32float","rg32uint","rg32sint","rgba16uint","rgba16sint","rgba16float","rgba32float","rgba32uint","rgba32sint","stencil8","depth16unorm","depth24plus","depth24plus-stencil8","depth32float","depth32float-stencil8",
"bc1-rgba-unorm","bc1-rgba-unorm-srgb","bc2-rgba-unorm","bc2-rgba-unorm-srgb","bc3-rgba-unorm","bc3-rgba-unorm-srgb","bc4-r-unorm","bc4-r-snorm","bc5-rg-unorm","bc5-rg-snorm","bc6h-rgb-ufloat","bc6h-rgb-float","bc7-rgba-unorm","bc7-rgba-unorm-srgb","etc2-rgb8unorm","etc2-rgb8unorm-srgb","etc2-rgb8a1unorm","etc2-rgb8a1unorm-srgb","etc2-rgba8unorm","etc2-rgba8unorm-srgb","eac-r11unorm","eac-r11snorm","eac-rg11unorm","eac-rg11snorm","astc-4x4-unorm","astc-4x4-unorm-srgb","astc-5x4-unorm","astc-5x4-unorm-srgb",
"astc-5x5-unorm","astc-5x5-unorm-srgb","astc-6x5-unorm","astc-6x5-unorm-srgb","astc-6x6-unorm","astc-6x6-unorm-srgb","astc-8x5-unorm","astc-8x5-unorm-srgb","astc-8x6-unorm","astc-8x6-unorm-srgb","astc-8x8-unorm","astc-8x8-unorm-srgb","astc-10x5-unorm","astc-10x5-unorm-srgb","astc-10x6-unorm","astc-10x6-unorm-srgb","astc-10x8-unorm","astc-10x8-unorm-srgb","astc-10x10-unorm","astc-10x10-unorm-srgb","astc-12x10-unorm","astc-12x10-unorm-srgb","astc-12x12-unorm","astc-12x12-unorm-srgb"],Kc=[,"1d","2d",
"2d-array","cube","cube-array","3d"],Lc=[,"uint8x2","uint8x4","sint8x2","sint8x4","unorm8x2","unorm8x4","snorm8x2","snorm8x4","uint16x2","uint16x4","sint16x2","sint16x4","unorm16x2","unorm16x4","snorm16x2","snorm16x4","float16x2","float16x4","float32","float32x2","float32x3","float32x4","uint32","uint32x2","uint32x3","uint32x4","sint32","sint32x2","sint32x3","sint32x4"],Mc=["vertex","instance"],R,Nc,Oc,Pc,S,Qc,T,U,V,Rc,W,Sc,X,Y,Z,Tc,pc,Uc,Vc,Wc,Xc,Yc,Zc;
function $c(a,b){return b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN}var ad=a=>{if(!noExitRuntime){if(g.onExit)g.onExit(a);ma=!0}da(a,new Ja(a))};function zb(a,b,c,d){a||(a=this);this.parent=a;this.Aa=a.Aa;this.Ka=null;this.id=tb++;this.name=b;this.mode=c;this.sa={};this.ua={};this.Pa=d}
Object.defineProperties(zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},tb:{get:function(){return 16384===(this.mode&61440)}},bb:{get:function(){return 8192===(this.mode&61440)}}});Pb();J=Array(4096);Fb(I,"/");M("/tmp",16895,0);M("/home",16895,0);M("/home/web_user",16895,0);
(()=>{M("/dev",16895,0);ab(259,{read:()=>0,write:(d,e,f,h)=>h});Gb("/dev/null",259);$a(1280,cb);$a(1536,db);Gb("/dev/tty",1280);Gb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ra(a).byteLength);return a[--b]};N("/dev","random",c);N("/dev","urandom",c);M("/dev/shm",16895,0);M("/dev/shm/tmp",16895,0)})();
(()=>{M("/proc",16895,0);var a=M("/proc/self",16895,0);M("/proc/self/fd",16895,0);Fb({Aa:()=>{var b=gb(a,"fd",16895,73);b.sa={Ja:(c,d)=>{var e=L(+d);c={parent:null,Aa:{eb:"fake"},sa:{La:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=Rb;g.FS_createDataFile=nb;g.FS_createPreloadedFile=mb;g.FS_unlink=Ib;g.FS_createLazyFile=Ub;g.FS_createDevice=N;
(function(){function a(){this.Ha={};this.Ia=1;this.create=function(b,c={}){var d=this.Ia++;c.Xa=1;c.object=b;this.Ha[d]=c;return d};this.get=function(b){if(b)return this.Ha[b].object};this.hb=function(b){this.Ha[b].Xa++};this.release=function(b){var c=this.Ha[b];c.Xa--;0>=c.Xa&&delete this.Ha[b]}}R||(Nc=Nc||new a,Oc=Oc||new a,Pc=Pc||new a,R=R||new a,S=S||new a,Qc=Qc||new a,T=T||new a,U=U||new a,V=V||new a,Rc=Rc||new a,W=W||new a,Sc=Sc||new a,X=X||new a,Y=Y||new a,Z=Z||new a,Tc=Tc||new a,pc=pc||new a,
Uc=Uc||new a,Vc=Vc||new a,Wc=Wc||new a,Xc=Xc||new a,Yc=Yc||new a)})();
var dd={r:function(a,b,c){Wb=c;try{var d=L(a);switch(b){case 21509:return d.va?0:-59;case 21505:if(!d.va)return-59;if(d.va.Ba.qb){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Xb();z[e>>2]=25856;z[e+4>>2]=5;z[e+8>>2]=191;z[e+12>>2]=35387;for(var f=0;32>f;f++)v[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.va?0:-59;case 21506:case 21507:case 21508:if(!d.va)return-59;if(d.va.Ba.rb)for(e=Xb(),b=[],f=0;32>f;f++)b.push(v[e+f+17>>0]);return 0;
case 21519:if(!d.va)return-59;e=Xb();return z[e>>2]=0;case 21520:return d.va?-28:-59;case 21531:e=Xb();if(!d.ua.pb)throw new H(59);return d.ua.pb(d,b,e);case 21523:if(!d.va)return-59;d.va.Ba.sb&&(f=[24,80],e=Xb(),na[e>>1]=f[0],na[e+2>>1]=f[1]);return 0;case 21524:return d.va?0:-59;case 21515:return d.va?0:-59;default:return-28}}catch(h){if("undefined"==typeof Vb||"ErrnoError"!==h.name)throw h;return-h.Da}},s:function(a,b,c,d){Wb=d;try{b=O(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":
L(a).path;if(0==e.length)throw new H(44);b=G(f+"/"+e)}var h=d?Xb():0;return Lb(b,c,h).Ea}catch(n){if("undefined"==typeof Vb||"ErrnoError"!==n.name)throw n;return-n.Da}},t:a=>{do{var b=B[a>>2];a+=4;var c=B[a>>2];a+=4;var d=B[a>>2];a+=4;b=O(b);Rb("/",Oa(b),!0,!0);nb(b,null,v.subarray(d,d+c),!0,!0,!0)}while(B[a>>2])},W:function(){return devicePixelRatio},U:function(a,b,c){a=hc(a);if(!a)return-4;a=0>gc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};D[b>>3]=a.width;D[c>>3]=a.height;return 0},o:(a,
b,c)=>y.copyWithin(a,b,b+c),ia:function(a,b){function c(d){jc(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},n:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-la.buffer.byteLength+65535>>>16;try{la.grow(e);pa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},T:function(a,b,c){a=hc(a);if(!a)return-4;a.width=b;a.height=c;
return 0},ja:function(a,b,c,d){return kc(a,b,c,d)},G:function(){if(void 0===Zc){var a=g.preinitializedWebGPUDevice,b={vb:S.create(a.queue)};Zc=R.create(a,b)}R.hb(Zc);return Zc},d:function(a){try{var b=L(a);Mb(b);return 0}catch(c){if("undefined"==typeof Vb||"ErrnoError"!==c.name)throw c;return c.Da}},q:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,h=b=0;h<c;h++){var n=B[a>>2],p=B[a+4>>2];a+=8;var m=e,t=n,q=p,u=f,w=v;if(0>q||0>u)throw new H(28);if(null===m.Ea)throw new H(8);if(1===(m.flags&2097155))throw new H(8);
if(16384===(m.node.mode&61440))throw new H(31);if(!m.ua.read)throw new H(28);var x="undefined"!=typeof u;if(!x)u=m.position;else if(!m.seekable)throw new H(70);var C=m.ua.read(m,w,t,q,u);x||(m.position+=C);var A=C;if(0>A){var Ma=-1;break a}b+=A;if(A<p)break;"undefined"!==typeof f&&(f+=A)}Ma=b}B[d>>2]=Ma;return 0}catch(ja){if("undefined"==typeof Vb||"ErrnoError"!==ja.name)throw ja;return ja.Da}},j:function(a,b,c,d,e){b=$c(b,c);try{if(isNaN(b))return 61;var f=L(a);Nb(f,b,d);Ia=[f.position>>>0,(F=f.position,
1<=+Math.abs(F)?0<F?+Math.floor(F/4294967296)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];z[e>>2]=Ia[0];z[e+4>>2]=Ia[1];f.Ta&&0===b&&0===d&&(f.Ta=null);return 0}catch(h){if("undefined"==typeof Vb||"ErrnoError"!==h.name)throw h;return h.Da}},p:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,h=b=0;h<c;h++){var n=B[a>>2],p=B[a+4>>2];a+=8;var m=Ob(e,v,n,p,f);if(0>m){var t=-1;break a}b+=m;"undefined"!==typeof f&&(f+=m)}t=b}B[d>>2]=t;return 0}catch(q){if("undefined"==typeof Vb||"ErrnoError"!==
q.name)throw q;return q.Da}},Z:function(){navigator.gpu?navigator.gpu.requestAdapter().then(function(a){a.requestDevice({requiredFeatures:["timestamp-query"]}).then(function(b){g.preinitializedWebGPUDevice=b;bd()})},function(){console.error("No WebGPU adapter; not starting")}):console.error("No support for WebGPU; not starting")},m:function(a){a=W.get(a).size;return cd((F=a,1<=+Math.abs(F)?0<F?+Math.floor(F/4294967296)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)),a>>>0},v:function(a){Qc.release(a)},
L:function(a,b){if(b){var c={};var d=B[b+4>>2];d&&(c.label=O(d));if(d=B[b+8>>2]){var e=c;b=B[b+12>>2];for(var f=[],h=0;h<d;++h){var n=f,p=n.push;var m=b+12*h;m={querySet:Z.get(B[m>>2]),queryIndex:B[m+4>>2],location:uc[B[m+8>>2]]};p.call(n,m)}e.timestampWrites=f}}a=T.get(a);return V.create(a.beginComputePass(c))},D:function(a,b){var c=B[b>>2],d=void 0;0!==c&&(d=4294967296*B[c+12>>2]+B[c+8>>2]);var e=B[b+8>>2],f=B[b+12>>2];c=[];for(var h=0;h<e;++h){var n=c,p=n.push;var m=f+56*h;var t=B[m+4>>2];if(0!==
t){var q=B[m+12>>2],u=B[m+16>>2];var w=m+24;w={r:D[w>>3],g:D[w+8>>3],b:D[w+16>>3],a:D[w+24>>3]};m={view:Y.get(t),resolveTarget:Y.get(B[m+8>>2]),clearValue:w,loadOp:Ac[q],storeOp:Hc[u]}}else m=void 0;p.call(n,m)}e=B[b+16>>2];e=0!==e?{view:Y.get(B[e>>2]),depthClearValue:oa[e+12>>2],depthLoadOp:Ac[B[e+4>>2]],depthStoreOp:Hc[B[e+8>>2]],depthReadOnly:0!==v[e+16>>0],stencilClearValue:B[e+28>>2],stencilLoadOp:Ac[B[e+20>>2]],stencilStoreOp:Hc[B[e+24>>2]],stencilReadOnly:0!==v[e+32>>0]}:void 0;d={label:void 0,
colorAttachments:c,depthStencilAttachment:e,occlusionQuerySet:Z.get(B[b+20>>2]),maxDrawCount:d};(c=B[b+4>>2])&&(d.label=O(c));if(c=B[b+24>>2]){b=B[b+28>>2];e=[];for(f=0;f<c;++f)h=e,n=h.push,p=b+12*f,p={querySet:Z.get(B[p>>2]),queryIndex:B[p+4>>2],location:Fc[B[p+8>>2]]},n.call(h,p);d.timestampWrites=e}a=T.get(a);return U.create(a.beginRenderPass(d))},x:function(a){a=T.get(a);return Qc.create(a.finish())},u:function(a){T.release(a)},k:function(a,b,c,d,e,f,h){f=$c(f,h);a=T.get(a);b=Z.get(b);e=W.get(e);
a.resolveQuerySet(b,c,d,e,f)},f:function(a,b,c){a=T.get(a);b=Z.get(b);a.writeTimestamp(b,c)},I:function(a,b,c,d){V.get(a).dispatchWorkgroups(b,c,d)},H:function(a){V.get(a).end()},F:function(a){V.release(a)},J:function(a,b,c,d,e){a=V.get(a);c=Rc.get(c);if(0==d)a.setBindGroup(b,c);else{for(var f=[],h=0;h<d;h++,e+=4)f.push(B[e>>2]);a.setBindGroup(b,c,f)}},K:function(a,b){a=V.get(a);b=Vc.get(b);a.setPipeline(b)},Y:function(a,b){a=Vc.get(a);return Tc.create(a.getBindGroupLayout(b))},O:function(){return 1},
aa:function(a,b){for(var c=Tc.get(B[b+8>>2]),d=B[b+12>>2],e=B[b+16>>2],f=[],h=0;h<d;++h){var n=f,p=n.push;var m=e+40*h;var t=B[m+8>>2],q=B[m+32>>2],u=B[m+36>>2],w=B[m+4>>2];t?(q=m+24,q=B[q>>2]+4294967296*z[q+4>>2],-1==q&&(q=void 0),m={binding:w,resource:{buffer:W.get(t),offset:4294967296*B[m+4+16>>2]+B[m+16>>2],size:q}}):m=q?{binding:w,resource:Sc.get(q)}:{binding:w,resource:Y.get(u)};p.call(n,m)}c={label:void 0,layout:c,entries:f};(b=B[b+4>>2])&&(c.label=O(b));a=R.get(a);return Rc.create(a.createBindGroup(c))},
c:function(a,b){var c=0!==v[b+24>>0],d={label:void 0,usage:B[b+8>>2],size:4294967296*B[b+4+16>>2]+B[b+16>>2],mappedAtCreation:c};(b=B[b+4>>2])&&(d.label=O(b));b=R.get(a);a={};d=W.create(b.createBuffer(d),a);c&&(a.Ob=2,a.Rb=[]);return d},M:function(a,b){if(b){var c={label:void 0};(b=B[b+4>>2])&&(c.label=O(b))}a=R.get(a);return T.create(a.createCommandEncoder(c))},_:function(a,b){var c=oc(B[b+8>>2]);var d=(d=b+12)?{module:Wc.get(B[d+4>>2]),entryPoint:O(B[d+8>>2]),constants:nc(B[d+12>>2],B[d+16>>2])}:
void 0;c={label:void 0,layout:c,compute:d};(b=B[b+4>>2])&&(c.label=O(b));a=R.get(a);return Vc.create(a.createComputePipeline(c))},X:function(a,b){var c=B[b+20>>2];if(c){var d=B[b+16>>2];var e=[];for(var f=0;f<c;++f)e.push(Cc[B[d+4*f>>2]])}b={type:Ec[B[b+8>>2]],count:B[b+12>>2],pipelineStatistics:e};a=R.get(a);return Z.create(a.createQuerySet(b))},ba:function(a,b){function c(f){if(f)return{operation:sc[B[f>>2]],srcFactor:rc[B[f+4>>2]],dstFactor:rc[B[f+8>>2]]}}function d(f){return{compare:tc[B[f>>2]],
failOp:Gc[B[f+4>>2]],depthFailOp:Gc[B[f+8>>2]],passOp:Gc[B[f+12>>2]]}}var e={label:void 0,layout:oc(B[b+8>>2]),vertex:function(f){if(f){var h=Wc.get(B[f+4>>2]),n=O(B[f+8>>2]),p=nc(B[f+12>>2],B[f+16>>2]);var m=B[f+20>>2];f=B[f+24>>2];if(m){for(var t=[],q=0;q<m;++q){var u=t,w=u.push;var x=f+24*q;if(x){var C=B[x+8>>2];if(2===C)var A=null;else{A=4294967296*B[x+4>>2]+B[x>>2];C=Mc[C];var Ma=B[x+12>>2];x=B[x+16>>2];for(var ja=[],ob=0;ob<Ma;++ob){var vc=ja,jd=vc.push,Na=x+24*ob;jd.call(vc,{format:Lc[B[Na>>
2]],offset:4294967296*B[Na+4+8>>2]+B[Na+8>>2],shaderLocation:B[Na+16>>2]})}A={arrayStride:A,stepMode:C,attributes:ja}}}else A=void 0;w.call(u,A)}m=t}else m=void 0;return{module:h,entryPoint:n,constants:p,buffers:m}}}(b+12),primitive:function(f){if(f)return{topology:Dc[B[f+4>>2]],stripIndexFormat:zc[B[f+8>>2]],frontFace:yc[B[f+12>>2]],cullMode:wc[B[f+16>>2]]}}(b+40),depthStencil:function(f){if(f)return{format:Q[B[f+4>>2]],depthWriteEnabled:0!==v[f+8>>0],depthCompare:tc[B[f+12>>2]],stencilFront:d(f+
16),stencilBack:d(f+32),stencilReadMask:B[f+48>>2],stencilWriteMask:B[f+52>>2],depthBias:z[f+56>>2],depthBiasSlopeScale:oa[f+60>>2],depthBiasClamp:oa[f+64>>2]}}(B[b+60>>2]),multisample:function(f){if(f)return{count:B[f+4>>2],mask:B[f+8>>2],alphaToCoverageEnabled:0!==v[f+12>>0]}}(b+64),fragment:function(f){if(f){var h=Wc.get(B[f+4>>2]),n=O(B[f+8>>2]),p=nc(B[f+12>>2],B[f+16>>2]),m=B[f+20>>2];f=B[f+24>>2];for(var t=[],q=0;q<m;++q){var u=t,w=u.push,x=f+16*q,C=B[x+4>>2];if(0===C)x=void 0;else{C=Q[C];var A=
(A=B[x+8>>2])?{alpha:c(A+12),color:c(A+0)}:void 0;x={format:C,blend:A,writeMask:B[x+12>>2]}}w.call(u,x)}return{module:h,entryPoint:n,constants:p,targets:t}}}(B[b+80>>2])};(b=B[b+4>>2])&&(e.label=O(b));a=R.get(a);return Uc.create(a.createRenderPipeline(e))},i:function(a,b){var c={label:void 0,addressModeU:qc[B[b+8>>2]],addressModeV:qc[B[b+12>>2]],addressModeW:qc[B[b+16>>2]],magFilter:xc[B[b+20>>2]],minFilter:xc[B[b+24>>2]],mipmapFilter:Bc[B[b+28>>2]],lodMinClamp:oa[b+32>>2],lodMaxClamp:oa[b+36>>2],
compare:tc[B[b+40>>2]]};(b=B[b+4>>2])&&(c.label=O(b));a=R.get(a);return Sc.create(a.createSampler(c))},ca:function(a,b){var c=B[b>>2],d=B[c+4>>2],e={label:void 0,code:""};(b=B[b+4>>2])&&(e.label=O(b));switch(d){case 5:d=B[c+12>>2];e.code=B.subarray(d>>2,(d>>2)+B[c+8>>2]);break;case 6:(c=B[c+8>>2])&&(e.code=O(c))}a=R.get(a);return Wc.create(a.createShaderModule(e))},R:function(a,b,c){a=R.get(a);b=Nc.get(b);var d=[B[c+16>>2],B[c+20>>2]];0!==d[0]&&(b.canvas.width=d[0]);0!==d[1]&&(b.canvas.height=d[1]);
b.configure({device:a,format:Q[B[c+12>>2]],usage:B[c+8>>2],alphaMode:"opaque"});return Oc.create(b)},h:function(a,b){var c={label:void 0,size:mc(b+16),mipLevelCount:B[b+32>>2],sampleCount:B[b+36>>2],dimension:Jc[B[b+12>>2]],format:Q[B[b+28>>2]],usage:B[b+8>>2]},d=B[b+4>>2];d&&(c.label=O(d));if(d=B[b+40>>2])b=B[b+44>>2],c.viewFormats=Array.from(z.subarray(b>>2,(b>>2)+d),function(e){return Q[e]});a=R.get(a);return X.create(a.createTexture(c))},e:function(a){a=R.Ha[a].vb;S.hb(a);return a},S:function(a,
b){a=hc(B[B[b>>2]+8>>2]).getContext("webgpu");if(!a)return 0;if(b=B[b+4>>2])a.Ub=O(b);return Nc.create(a)},ea:function(a){S.release(a)},w:function(a,b,c){a=S.get(a);b=Array.from(z.subarray(c>>2,(c>>2)+b),function(d){return Qc.get(d)});a.submit(b)},l:function(a,b,c,d,e,f){c=$c(c,d);a=S.get(a);b=W.get(b);a.writeBuffer(b,c,y.subarray(e,e+f),0,f)},fa:function(a,b,c,d,e,f){a=S.get(a);var h=X.get(B[b+4>>2]),n=b+12,p=B[e+16>>2],m=B[e+20>>2];a.writeTexture({texture:h,mipLevel:B[b+8>>2],origin:{x:B[n>>2],
y:B[n+4>>2],z:B[n+8>>2]},aspect:Ic[B[b+24>>2]]},y.subarray(c,c+d),{offset:4294967296*B[e+4+8>>2]+B[e+8>>2],bytesPerRow:4294967295===p?void 0:p,rowsPerImage:4294967295===m?void 0:m},mc(f))},A:function(a,b,c,d,e){U.get(a).draw(b,c,d,e)},z:function(a){U.get(a).end()},y:function(a){U.release(a)},B:function(a,b,c,d,e){a=U.get(a);c=Rc.get(c);if(0==d)a.setBindGroup(b,c);else{for(var f=[],h=0;h<d;h++,e+=4)f.push(B[e>>2]);a.setBindGroup(b,c,f)}},C:function(a,b){a=U.get(a);b=Uc.get(b);a.setPipeline(b)},$:function(a,
b){a=Uc.get(a);return Tc.create(a.getBindGroupLayout(b))},N:function(a){Sc.release(a)},P:function(a){Wc.release(a)},Q:function(a){Nc.release(a)},E:function(a){a=Oc.get(a);return Y.create(a.getCurrentTexture().createView())},V:function(a){Oc.release(a)},da:function(a,b){if(b){var c=B[b+20>>2];var d=B[b+28>>2];c={format:Q[B[b+8>>2]],dimension:Kc[B[b+12>>2]],baseMipLevel:B[b+16>>2],mipLevelCount:4294967295===c?void 0:c,baseArrayLayer:B[b+24>>2],arrayLayerCount:4294967295===d?void 0:d,aspect:Ic[B[b+32>>
2]]};(b=B[b+4>>2])&&(c.label=O(b))}a=X.get(a);return Y.create(a.createView(c))},g:function(a){a=X.get(a);return Q.indexOf(a.format)},ga:function(a){return X.get(a).height},ha:function(a){return X.get(a).width},b:function(a){X.release(a)},a:function(a){Y.release(a)}};
(function(){function a(c){r=c=c.exports;la=r.ka;pa();qa=r.pa;sa.unshift(r.la);Aa("wasm-instantiate");return c}var b={a:dd};za("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return l("Module.instantiateWasm callback failed with error: "+c),!1}Ha(b,function(c){a(c.instance)});return{}})();var bd=g._entry_point=()=>(bd=g._entry_point=r.ma)(),ed=g._main=(a,b)=>(ed=g._main=r.na)(a,b),lc=a=>(lc=r.oa)(a),cd=a=>(cd=r.qa)(a),fd=a=>(fd=r.ta)(a);
g.___emscripten_embedded_file_data=20444;g.___start_em_js=23289;g.___stop_em_js=23688;g.addRunDependency=za;g.removeRunDependency=Aa;g.FS_createPath=Rb;g.FS_createDataFile=nb;g.FS_createLazyFile=Ub;g.FS_createDevice=N;g.FS_unlink=Ib;g.FS_createPreloadedFile=mb;var gd;ya=function hd(){gd||kd();gd||(ya=hd)};
function ld(a=[]){var b=ed;a.unshift(ca);var c=a.length,d=fd(4*(c+1)),e=d>>2;a.forEach(h=>{var n=z,p=e++,m=Wa(h)+1,t=fd(m);Xa(h,y,t,m);n[p]=t});z[e]=0;try{var f=b(c,d);ad(f)}catch(h){h instanceof Ja||"unwind"==h||da(1,h)}}
function kd(){var a=ba;function b(){if(!gd&&(gd=!0,g.calledRun=!0,!ma)){g.noFSInit||Qb||(Qb=!0,Pb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?N("/dev","stdin",g.stdin):Hb("/dev/tty","/dev/stdin"),g.stdout?N("/dev","stdout",null,g.stdout):Hb("/dev/tty","/dev/stdout"),g.stderr?N("/dev","stderr",null,g.stderr):Hb("/dev/tty1","/dev/stderr"),Lb("/dev/stdin",0),Lb("/dev/stdout",1),Lb("/dev/stderr",1));ub=!1;Ka(sa);Ka(ta);if(g.onRuntimeInitialized)g.onRuntimeInitialized();md&&ld(a);if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Ka(va)}}if(!(0<E)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();Ka(ra);0<E||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var md=!0;g.noInitialRun&&(md=!1);kd();
